#ifndef AMIGA_SHELL_PROTO_DOS_H
#define AMIGA_SHELL_PROTO_DOS_H

#include <dos/dos.h>
#include <dos/notify.h>
#include <utility/tagitem.h>
#include <stdarg.h>

struct DosLibrary;
extern struct DosLibrary *DOSBase;

struct CommandLineInterface;
struct Task;
/* Exec's signature, not a DOS one -- FindTask() is declared here because DOS
   callers reach it through <proto/dos.h>, but the type is exec.library's and
   must match compat/aros-real/include/proto/exec.h exactly.  The two used to
   disagree (APTR here, struct Task * there), which no translation unit
   noticed until one included both trees.  Guarded because the test-only
   AMIGA_EXEC_COMPAT_ENABLED build #defines FindTask to an opaque shim that
   declares itself. */
#ifndef FindTask
struct Task *FindTask(CONST_STRPTR name);
#endif
BOOL StartNotify(struct NotifyRequest *request);
void EndNotify(struct NotifyRequest *request);

struct CommandLineInterface *Cli(void);
BOOL SetPrompt(CONST_STRPTR prompt);
LONG VPrintf(CONST_STRPTR format, APTR arguments);
LONG SystemTagList(CONST_STRPTR command, const struct TagItem *tags);
struct Process;
/* Starts an AmigaDOS process on NP_Entry.  See src/native_process.c for what
   is honoured and what is accepted but not acted on. */
struct Process *CreateNewProc(const struct TagItem *tags);
struct Process *CreateNewProcTags(IPTR tag1, ...);
BPTR OpenFromLock(BPTR handle);
BPTR DupLockFromFH(BPTR fh);
LONG WriteChars(CONST_STRPTR buf, ULONG buflen);
LONG NameFromFH(BPTR fh, STRPTR buffer, LONG length);

/* On real AmigaOS this varargs convenience form of SystemTagList() is
   generated by the compiler's own stub headers (SAS/C's autodoc pragmas,
   GCC+ixemul's inline/dos.h); AROS's checked-out include tree has neither,
   so a caller written against them -- Vim's os_amiga.c, among others --
   finds nothing to link against. This builds the same tag array by hand and
   forwards to the one real entry point. Terminated by TAG_DONE, matching
   every real Amiga *Tags() wrapper's calling convention. */
static inline LONG SystemTags(CONST_STRPTR command, ...)
{
    struct TagItem tags[32];
    size_t count = 0;
    va_list arguments;
    IPTR tag;

    va_start(arguments, command);
    while (count < sizeof(tags) / sizeof(tags[0]) - 1) {
        tag = va_arg(arguments, IPTR);
        if (tag == TAG_DONE)
            break;
        tags[count].ti_Tag = tag;
        tags[count].ti_Data = va_arg(arguments, IPTR);
        count++;
    }
    va_end(arguments);
    tags[count].ti_Tag = TAG_DONE;
    return SystemTagList(command, tags);
}

#endif
